language: go
go_import_path: github.com/andyzhangx/azurefile-csi-driver

env:
  global:
    - GO111MODULE=off

go:
  - "1.11.4"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/rexray/gocsi/csc
  - sudo apt update && sudo apt install cifs-utils -y

script:
  - hack/verify-all.sh
  - make test
  - make azurefile
  - make integration-test
  - make azurefile-windows
  - make azurefile-container
