language: go
go_import_path: github.com/andyzhangx/azurefile-csi-driver

env:
  global:
    - GO111MODULE=off

go:
  - "1.11.4"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/rexray/gocsi/csc

script:
  - hack/verify-all.sh
  - make test
  - make azurefile
  - go test -covermode=count -coverprofile=profile.cov ./pkg/...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - test/e2e/run-test.sh
  - make azurefile-windows
  - make azurefile-container
