apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: csi-azurefile
    readOnly: false
    volumeHandle: arbitrary-volumeid
    volumeAttributes:
      sharename: k8stest
    nodePublishSecretRef:
      name: azure-secret
      namespace: default
