apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #If set as "Delete" file share would be removed after pvc deletion
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: arbitrary-volumeid
    volumeAttributes:
      shareName: EXISTING_FILE_SHARE_NAME
    nodePublishSecretRef:
      name: azure-secret
      namespace: default
